# Generated by Django 4.2.7 on 2023-11-27 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('personal_number', models.CharField(max_length=10)),
                ('nip', models.CharField(max_length=25)),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('eselon', models.CharField(max_length=10)),
                ('jabatan', models.CharField(max_length=25)),
                ('area_kerja', models.CharField(max_length=100)),
                ('sub_area_kerja', models.CharField(max_length=100)),
                ('unit_kerja', models.CharField(max_length=100)),
                ('level_id', models.CharField(max_length=25)),
                ('role_pengguna', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nomor_handphone', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
