# Generated by Django 4.2.7 on 2023-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('kode_perusahaan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_perusahaan', models.CharField(max_length=75)),
                ('grup_usaha', models.CharField(max_length=75)),
                ('kategori_bank', models.CharField(max_length=50)),
                ('negara_asal', models.CharField(max_length=255)),
                ('kategori_perusahaan', models.CharField(max_length=50)),
                ('alamat_perusahaan', models.CharField(max_length=255)),
                ('deskripsi_perusahaan', models.CharField(max_length=255)),
                ('sektor_industri', models.CharField(max_length=50)),
                ('logo_perusahaan', models.ImageField(upload_to='logo-perusahaan/')),
                ('fasilitas_pinjaman', models.CharField(max_length=75)),
                ('currency', models.CharField(max_length=25)),
                ('plafond', models.BigIntegerField()),
            ],
        ),
    ]
