# Generated by Django 4.2.7 on 2023-11-27 04:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='data_financial',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='data_financial/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='dokumen_agunan',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dokumen_agunan/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='dokumentasi_kredit',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dokumentasi_kredit/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='identitas_perusahaan',
            field=models.ImageField(default=1, upload_to='identitas_perusahaan/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='lain_lain',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='lain_lain/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='legalitas_usaha',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='legalitas_usaha/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='kode_perusahaan',
            field=models.CharField(max_length=50),
        ),
    ]
